### ISSUE TITLE
reversed folder structure hindering package import

### ISSUE THREAD

**Issue by dhemgren** [mikemonteith/react-native-android-checkbox#1]
'import com.mikemonteith.reactnativeandroidcheckbox.CheckboxPackage;'
results in package not found on building due to folder structure being /mikemonteith/com/
and not /com/mikemonteith

building works using
'import mikemonteith.com.reactnativeandroidcheckbox.CheckboxPackage;'

**Comment by mikemonteith** [comment]
Oh wow! Not sure how that happened. I'll fix it today

**Comment by dhemgren** [comment]
Great! Thanks for an awesome checkbox!
