### ISSUE TITLE
is it possible to change the color of checkbox & ripple

### ISSUE THREAD

**Issue by prscX** [mikemonteith/react-native-android-checkbox#15]
Can you please guide me on how to change the color of checkbox and its ripple. Basically I want to customize this based on our app color theme.

**Comment by mikemonteith** [comment]
Hi.

You would have to add a new prop, similar to the way the disabled prop works: https://github.com/mikemonteith/react-native-android-checkbox/blob/8d72a6c42f995ad3ce795d34571dcc5e1d9a8563/android/src/main/java/com/mikemonteith/reactnativeandroidcheckbox/CheckboxManager.java#L53-L56

Have a look at this android method to change the button color
https://developer.android.com/reference/android/widget/CompoundButton.html#setButtonTintList(android.content.res.ColorStateList)

**Comment by mikemonteith** [comment]
Let me know if you can create a pull request to do this, or maybe someone else will? I don't have much free time at the moment, sorry.

**Comment by mikemonteith** [comment]
I've managed to find some time. Working on this now, so will _hopefully_ have a new release tonight

**Comment by mikemonteith** [comment]
If you update to react-native-android-checkbox v3.1.1, you can now use the `tintColor` prop.

I've noticed that the latest react-native version has a native CheckBox component so I probably won't be maintaining this library any more, however there is no color option on the native component so you can still use this one if you need color

**Comment by mikemonteith** [comment]
If you wanted to use the native CheckBox, you could probably change the color with android theme settings, but you wont be able to change the color dynamically.

I _think_ like this

In your `android/app/res/values/styles.xml` file:
```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:checkboxStyle">@style/customCheckBoxStyle</item>
    </style>

    <style name="customCheckBoxStyle" parent="@android:style/Widget.CompoundButton.CheckBox">
        <item name="android:buttonTint">#FF0000</item>
    </style>

</resources>
```

**Comment by prscX** [comment]
Hi @mikemonteith, 

Apologize for the delay response. Somehow it got missed

I would really like to appreciate you for finding time from your busy schedule and enabling the color feature

Thanks
Pranav
