### ISSUE TITLE
Consider using rnpm in installation instructions

### ISSUE THREAD

**Issue by mkonicek** [mikemonteith/react-native-android-checkbox#3]
Hey @mikemonteith, awesome that you released this!

Just wanted to ping you that there's a tool that makes it very easy for people to add your module to their apps: https://github.com/rnpm/rnpm

It would simplify the installation instructions in the README.

I looked on Twitter but couldn't find your handle so pinging you here, feel free to close this issue :)

**Comment by ErikCupal** [comment]
Thanks a lot as well @mikemonteith ! 

It's even easier now. We can type `react-native link` and it does everything for you. It's worth adding to README imho.
